spring.application.name=StriptKillGameDemo2

# ===================== MongoDB config =====================
spring.data.mongodb.uri=mongodb://localhost:27017/stript_kill_game

# ===================== Redis config =======================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=5000

# ===================== JWT config =========================
jwt.secret=c3RyaXB0LWtpbGwtZ2FtZS1kZW1vMi1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tMjAyNg==
jwt.access-token-expiration=7200
jwt.refresh-token-expiration=2592000